-- populando tabela times

INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612737,'Atlanta','Hawks',1949,'State Farm Arena','Tony Ressler');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612740,'New Orleans','Pelicans',2002,'Smoothie King Center','Tom Benson');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612741,'Chicago','Bulls',1966,'United Center','Jerry Reinsdorf');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612742,'Dallas','Mavericks',1980,'American Airlines Center','Mark Cuban');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612743,'Denver','Nuggets',1976,'Pepsi Center','Stan Kroenke');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612746,'LA Clippers','Clippers',1970,'Staples Center','Steve Ballmer');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612748,'Miami','Heat',1988,'AmericanAirlines Arena','Micky Arison');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612749,'Milwaukee','Bucks',1968,'Fiserv Forum','Wesley Edens & Marc Lasry');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612752,'New York','Knicks',1946,'Madison Square Garden','Cablevision (James Dolan)');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612753,'Orlando','Magic',1989,'Amway Center','Rick DeVos');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612754,'Indiana','Pacers',1976,'Bankers Life Fieldhouse','Herb Simon');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612755,'Philadelphia','76ers',1949,'Wells Fargo Center','Joshua Harris');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612756,'Phoenix','Suns',1968,'Talking Stick Resort Arena','Robert Sarver');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612757,'Portland','Trail Blazers',1970,'Moda Center','Paul Allen');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612758,'Sacramento','Kings',1948,'Golden 1 Center','Vivek Ranadive');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612760,'Oklahoma City','Thunder',1967,'Chesapeake Energy Arena','Clay Bennett');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612761,'Toronto','Raptors',1995,'Scotiabank Arena','Maple Leaf Sports and Entertainment');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612763,'Memphis','Grizzlies',1995,'FedExForum','Robert Pera');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612765,'Detroit','Pistons',1948,'Little Caesars Arena','Tom Gores');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612766,'Charlotte','Hornets',1988,'Spectrum Center','Michael Jordan');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612739,'Cleveland','Cavaliers',1970,'Quicken Loans Arena','Dan Gilbert');
INSERT INTO times(TIME_ID,NOME_TIME,APELIDO,ANO_FUNDACAO,ARENA,DONO_TIME) VALUES (1610612744,'Golden State','Warriors',1946,'Chase Center','Joe Lacob');
